import Head from 'next/head';
import styles from '../styles/Home.module.css';

type Props = {
  title: string;
};

export default function Home({ title = 'React Avançado' }: Props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>{title}</h1>
    </div>
  );
}
